---
name: Leo Puentes
description: Blog de conocimiento Motivación - Programación - Inversión
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: leopolseo@gmail.com
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  Leo:
    name: Leo Puentes
    site: https://leopuentes.me
    avatar: "/assets/images/avatar1.jpg"
    bio: 'Impulsar el potencial de Internet es mi pasión. He decidido crear este blog
      donde deseo y quiero compartir todo el conocimiento que he aprendido y el que
      voy aprendiendo. Me gusta enseñar y junto a ello he desarrollado habilidades
      para Motivar, Programar e Invertir. Todo lo que soy esta en este blog, espero
      sea de tu agrado y podamos aprender. '
    email: jholepual@gmail.com
    twitter: 'https://twitter.com/elsermillonario'
    facebook: 'https://www.facebook.com/elsermillonarioo'
    instagram: 'https://www.instagram.com/elsermillonario'
    tiktok: 'https://bit.ly/tiktokelsermillonario'
    youtube: 'https://www.youtube.com/c/ElSerMillonario'
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: Leo
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
disqus: "leopuentes"
